// Builds public/assets/icons.svg from the Remix Icon package.
//   npm pack remixicon --pack-destination /tmp && tar -xzf /tmp/remixicon-*.tgz -C /tmp
//   node scripts/vendor-icons.mjs /tmp/package
// Add a name to ICONS and re-run to vendor another icon. Each symbol uses
// currentColor via CSS, so icons follow the active theme.
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { join } from 'node:path';

/** sprite id → Remix icon file name (without .svg) */
const ICONS = {
  home: 'home-line', links: 'links-line', book: 'book-open-line', palette: 'palette-line', logout: 'logout-box-r-line',
  pencil: 'pencil-line', trash: 'delete-bin-line', add: 'add-line', close: 'close-line',
  download: 'download-line', upload: 'upload-line', 'arrow-right': 'arrow-right-line',
  search: 'search-line', user: 'user-line', 'user-add': 'user-add-line', bookmark: 'bookmark-line',
  external: 'external-link-line', chart: 'bar-chart-line', eye: 'eye-line', settings: 'settings-3-line',
  info: 'information-line', warning: 'error-warning-line', check: 'check-line', refresh: 'refresh-line',
  database: 'database-2-line', save: 'save-line', moon: 'moon-line', sun: 'sun-line',
  'arrow-up': 'arrow-up-line', 'arrow-down': 'arrow-down-line', question: 'question-line',
};

const root = process.argv[2];
if (!root) throw new Error('usage: node scripts/vendor-icons.mjs <path to extracted remixicon package>');
const version = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8')).version;

function findSvg(dir, name) {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      const hit = findSvg(full, name);
      if (hit) return hit;
    } else if (entry === `${name}.svg`) return full;
  }
  return null;
}

const symbols = Object.entries(ICONS).map(([id, file]) => {
  const path = findSvg(join(root, 'icons'), file);
  if (!path) throw new Error(`icon not found: ${file}`);
  const svg = readFileSync(path, 'utf8');
  const inner = svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').trim();
  return `  <symbol id="${id}" viewBox="0 0 24 24">${inner}</symbol>`;
});

const out = `<!--
  Icons by Remix Icon ${version} (https://remixicon.com), Copyright (c) Remix Design,
  used under the Remix Icon License v1.0: https://github.com/Remix-Design/RemixIcon/blob/master/License
  Generated by scripts/vendor-icons.mjs; edit that file, not this one.
-->
<svg xmlns="http://www.w3.org/2000/svg" style="display:none">
${symbols.join('\n')}
</svg>
`;
writeFileSync(new URL('../public/assets/icons.svg', import.meta.url), out);
console.log(`wrote ${symbols.length} icons from Remix Icon ${version}`);
